name: Add Tags to Release

on:
  release:
    types: [published]

jobs:
  build-if-needed:
    runs-on: ubuntu-latest
    steps:
    - name: Check whether we need to build this or not
      id: need_to_build
      run: |
        function image_exists() {
            curl --silent -f -lSL https://quay.io/v1/repositories/redhat-cop/dynamic-rbac-operator/tags/$1 > /dev/null
        }
        if image_exists ${{ github.sha }}; then
            echo "Image exists - not building"
            echo ::set-output name=need_to_build::0
        else 
            echo "Image needs to be built"
            echo ::set-output name=need_to_build::1
        fi
    - uses: actions/checkout@v2
      if: steps.need_to_build.outputs.need_to_build == 1
    - name: "Build and Push Image"
      if: steps.need_to_build.outputs.need_to_build == 1
      uses: docker/build-push-action@v1
      with:
        dockerfile: Dockerfile
        username: ${{ secrets.OPERATOR_REGISTRY_USERNAME }}
        password: ${{ secrets.OPERATOR_REGISTRY_PASSWORD }}
        registry: quay.io
        repository: redhat-cop/dynamic-rbac-operator
        push: true
        tags: "${{ github.sha }},main"

  release:
    runs-on: ubuntu-latest
    needs: build-if-needed
    steps:
    - uses: actions/checkout@v2
    - name: tag with release version
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: redhat-cop/dynamic-rbac-operator
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: quay.io
        registry_username: ${{ secrets.OPERATOR_REGISTRY_USERNAME }}
        registry_password: ${{ secrets.OPERATOR_REGISTRY_PASSWORD }}
    - name: tag with latest
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: redhat-cop/dynamic-rbac-operator
        image_old_tag: ${{ github.sha }}
        registry: quay.io
        registry_username: ${{ secrets.OPERATOR_REGISTRY_USERNAME }}
        registry_password: ${{ secrets.OPERATOR_REGISTRY_PASSWORD }}
